_wandb:
    value:
        cli_version: 0.19.3
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": train_loss_step
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_acc_step
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_acc_epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 9
                - 41
                - 49
                - 55
                - 63
                - 103
            "2":
                - 1
                - 9
                - 41
                - 49
                - 55
                - 63
                - 103
            "3":
                - 7
                - 14
                - 23
                - 55
                - 66
            "4": 3.11.11
            "5": 0.19.3
            "8":
                - 5
            "12": 0.19.3
            "13": darwin-arm64
