name: "Run tests"

on:
  push:
    branches: [ main, updated-code-structure ]
  pull_request:
    branches: [ main, updated-code-structure ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-latest", "macos-latest"]
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # caching pip dependencies

    - name: Set PYTHONPATH for Windows
      if: runner.os == 'Windows'
      run: echo "PYTHONPATH=$(pwd)/src" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8
      shell: pwsh

    - name: Set PYTHONPATH for Unix
      if: runner.os != 'Windows'
      run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV
      shell: bash

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt

    # Add DVC setup step
    - uses: iterative/setup-dvc@v1

    # Pull data using DVC
    - name: Get data
      run: dvc pull
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

    - name: Test with pytest
    - name: Test with coverage
      run: |
        coverage run -m pytest -v # Run tests with coverage measurement
        coverage report
