name: "Run tests"

on:
  push:
    branches: [ main, updated-code-structure ]
  pull_request:
    branches: [ main, updated-code-structure ]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD/src" >> $GITHUB_ENV
    - name: Test with pytest
      run: |
        pytest -v
